#!/bin/bash

set -e
source_rel() {
  source "${BASH_SOURCE%/*}/$1"
}

source_rel "printer.sh"
source_rel "util.sh"

print_usage_and_exit() {
  cat <<-EOF
Usage:
  freight <version store> <app config...>

  version store: File that stores the currently deployed version of each app.
    Will be created if it does not exist. Should be consistent between deployments

  app config: File or files that contain config for applications. These are bash
    files, with a DSL-like syntax for defining apps:

    my-server() {
      url=https://example.com/my_git_repo
      version=3.1.4
    }
    app my-server

    The apps and files will be processed/ loaded in order.

  NOTE: All config files are bash scripts, this makes the tool easy to develop
    but poses a security hole. Don't put untrusted content in your config or
    verion files!

EOF
  exit 1
}

flags_working_dir="."
parse_flags $@
subcommand="${args[0]}" 

case "$subcommand" in
  "upgrade")
    source_rel "upgrade.sh" ;;
  "init")
    source_rel "init.sh" ;;
  *)
    print_usage_and_exit ;;
esac
